platform :ios, '10.0'

target 'TheMovieDB' do
  use_frameworks!
  
  pod 'TinyConstraints', '3.1.0'
  pod 'Reveal-SDK', :configurations => ['Debug']
  pod 'Alamofire', '4.6.0'
  pod 'AlamofireImage', '3.3.0'
  pod 'RealmSwift', '3.7.5'
  pod 'lottie-ios', '2.5.0'
  
  target 'TheMovieDBTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'TheMovieDBAPITests' do
      inherit! :search_paths
      # Pods for testing
  end

end
